# Generated by Django 2.1.2 on 2018-11-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profilepic',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
